name: 'Sample Workflow'
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Enter you email address.'
        required: true
        default: 'xyz@example.com'
jobs:
  clock-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hey there! The time of the runner is "
      - run: timedatectl
  greetings-job:
    needs: clock-job
    runs-on: ubuntu-latest
    steps:
      - name: CINotify Email
        uses: cinotify/github-action@v1.1.0
        with:
          to: ${{ github.event.inputs.email }}
          subject: 'Hello from Rimjhim'
          body: 'Hey there! Hope you are doing good. It is me, Rimjhim doing my Coding Week. Great to meet you!'
